services:
  database:
    build:
      context: .
      dockerfile: dockerfile.db
      tags:
        - 'arkdich/music-service-db'
    container_name: music-service-db-container
    env_file:
      - .env.local
    ports:
      - '8000:5432'
    volumes:
      - ./pg-logs:/db/logs
    environment:
      - POSTGRES_INITDB_ARGS=-c shared_preload_libraries='pg_cron' -c cron.database_name='music_service'
  api:
    build:
      context: .
      dockerfile: dockerfile.api
      tags:
        - 'arkdich/music-service-api'
    depends_on:
      - database
    container_name: music-service-api-container
    environment:
      - PORT_DB=5432
      - DB_HOST=database
    ports:
      - '4000:4000'
