services:
  database:
    build:
      context: .
      dockerfile: dockerfile.db
      tags:
        - 'music-service-db-image'
    container_name: music-service-db-container
    env_file:
      - .env.local
    ports:
      - '8000:5432'
  api:
    build:
      context: .
      dockerfile: dockerfile.api
      tags:
        - 'music-service-api-image'
    depends_on:
      - database
    container_name: music-service-api-container
    environment:
      - PORT_DB=5432
